name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-xdist pytest-cov
      shell: powershell

    - name: Check working directory
      run: |
        echo "Current working directory: $PWD"
        dir
      shell: powershell

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$env:PYTHONPATH;$env:GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PYTHONPATH after setting: $env:PYTHONPATH"
      shell: powershell

    - name: Run tests with coverage
      run: |
        pytest --cache-clear test_parsing.py -n 2 --cov=parser --cov-report=xml
      shell: powershell
      working-directory: ${{ github.workspace }}

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: parser.log

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
