name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-xdist pytest-cov flake8 black
      shell: powershell

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH;$env:GITHUB_WORKSPACE" >> $GITHUB_ENV
      shell: powershell

    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=120
      shell: powershell

    - name: Format with black
      run: |
        black . --check
      shell: powershell

    - name: Run tests with coverage
      run: |
        pytest --cache-clear test_parsing.py -n auto --cov=parser --cov-report=xml
      shell: powershell

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: parser.log

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
